export { Border1 } from './Border1'
export { Border2 } from './Border2'
export { Border3 } from './Border3'
export { Border4 } from './Border4'
export { Border5 } from './Border5'
export { Border6 } from './Border6'
